# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6551a3e7ae975100782a192e1d845b229569367dda19486311bd8bab60689db390a4a06aa7d6c8fc074aa756d4079c177478661300e18ed8067117f0055062c9

test:
  secret_key_base: d69f98109d933e1a80e28b4e831d289c13dfad071c3a2a4a0da288cbf8341c192723059c83703323fc50360bb92202048b44175698295a4eb532c3737920cbfe

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
